# Generated by Django 5.2.14 on 2026-05-24 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaSolicitud', models.DateField(auto_now_add=True, help_text='Fecha de creación de la solicitud')),
                ('descripcionSolicitud', models.CharField(help_text='Ingrese la descripción de la solicitud', max_length=300)),
                ('direccionRecogidaSolicitud', models.CharField(blank=True, help_text='Ingrese la dirección de recogida', max_length=200, null=True)),
                ('direccionEntregaSolicitud', models.CharField(help_text='Ingrese la dirección de entrega', max_length=200)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='usuarios.cliente')),
                ('tipoEstado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estados_solicitud', to='core.tipomaestra')),
                ('tipoMotivoRechazo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='motivos_rechazo_solicitud', to='core.tipomaestra')),
                ('tipoServicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios_solicitud', to='core.tipomaestra')),
                ('tipoZona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zonas_solicitud', to='core.tipomaestra')),
            ],
            options={
                'verbose_name': 'solicitud',
                'verbose_name_plural': 'solicitudes',
            },
        ),
    ]
