# Generated by Django 5.2.14 on 2026-05-25 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tipomaestra_options_and_more'),
        ('solicitudes', '0001_initial'),
        ('usuarios', '0002_alter_cliente_options_alter_domiciliario_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitud',
            options={'ordering': ['-fechaSolicitud', '-id'], 'verbose_name': 'solicitud', 'verbose_name_plural': 'solicitudes'},
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='cliente',
            field=models.ForeignKey(db_column='CLIE_ID', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='usuarios.cliente'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='descripcionSolicitud',
            field=models.CharField(db_column='SOLI_DESCRIPCION', help_text='Ingrese la descripción de la solicitud', max_length=300),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='direccionEntregaSolicitud',
            field=models.CharField(db_column='SOLI_DIR_ENTREGA', help_text='Ingrese la dirección de entrega', max_length=200),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='direccionRecogidaSolicitud',
            field=models.CharField(blank=True, db_column='SOLI_DIR_RECOGIDA', help_text='Ingrese la dirección de recogida', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fechaSolicitud',
            field=models.DateField(auto_now_add=True, db_column='SOLI_FECHA', help_text='Fecha de creación de la solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='id',
            field=models.AutoField(db_column='SOLI_ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipoEstado',
            field=models.ForeignKey(db_column='TIPO_ESTADO', on_delete=django.db.models.deletion.PROTECT, related_name='estados_solicitud', to='core.tipomaestra'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipoMotivoRechazo',
            field=models.ForeignKey(blank=True, db_column='TIPO_MOTIVO_RECHAZO', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='motivos_rechazo_solicitud', to='core.tipomaestra'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipoServicio',
            field=models.ForeignKey(db_column='TIPO_SERVICIO', on_delete=django.db.models.deletion.PROTECT, related_name='servicios_solicitud', to='core.tipomaestra'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipoZona',
            field=models.ForeignKey(db_column='TIPO_ZONA', on_delete=django.db.models.deletion.PROTECT, related_name='zonas_solicitud', to='core.tipomaestra'),
        ),
        migrations.AlterModelTable(
            name='solicitud',
            table='TBL_SOLICITUDES',
        ),
    ]
