# Generated by Django 5.2.14 on 2026-05-24 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMaestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTipo', models.CharField(help_text='Ingrese el nombre del tipo', max_length=100)),
                ('codigoTipo', models.CharField(blank=True, help_text='Ingrese el código del tipo', max_length=30, null=True, unique=True)),
                ('esTabla', models.BooleanField(default=False)),
                ('padreTipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subtipos', to='core.tipomaestra')),
            ],
            options={
                'verbose_name': 'tipo maestro',
                'verbose_name_plural': 'tipos maestros',
            },
        ),
    ]
