# Generated by Django 5.2.14 on 2026-05-25 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipomaestra',
            options={'ordering': ['padreTipo_id', 'nombreTipo'], 'verbose_name': 'tipo maestro', 'verbose_name_plural': 'tipos maestros'},
        ),
        migrations.AlterField(
            model_name='tipomaestra',
            name='codigoTipo',
            field=models.CharField(blank=True, db_column='TIMA_CODIGO', help_text='Ingrese el código del tipo', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tipomaestra',
            name='esTabla',
            field=models.BooleanField(db_column='IS_TABLA', default=False),
        ),
        migrations.AlterField(
            model_name='tipomaestra',
            name='id',
            field=models.AutoField(db_column='TIMA_ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipomaestra',
            name='nombreTipo',
            field=models.CharField(db_column='TIMA_NOMBRE', help_text='Ingrese el nombre del tipo', max_length=100),
        ),
        migrations.AlterField(
            model_name='tipomaestra',
            name='padreTipo',
            field=models.ForeignKey(blank=True, db_column='PADRE_ID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subtipos', to='core.tipomaestra'),
        ),
        migrations.AlterModelTable(
            name='tipomaestra',
            table='TBL_TIPOS_MAESTRA',
        ),
    ]
