# Generated by Django 5.2.14 on 2026-05-24 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignaciones', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEstadoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCambioHistorial', models.DateTimeField(auto_now_add=True)),
                ('observacionHistorial', models.CharField(blank=True, help_text='Ingrese una observación', max_length=300, null=True)),
                ('tipoEstado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estados_historial_entrega', to='core.tipomaestra')),
            ],
            options={
                'verbose_name': 'historial estado entrega',
                'verbose_name_plural': 'historial estados entrega',
            },
        ),
        migrations.CreateModel(
            name='SeguimientoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaEstimadaSeguimiento', models.DateTimeField(help_text='Ingrese la fecha estimada de entrega')),
                ('fechaRealSeguimiento', models.DateTimeField(blank=True, help_text='Ingrese la fecha real de entrega', null=True)),
                ('cumplimientoSeguimiento', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CUMPLIDO', 'Cumplido'), ('INCUMPLIDO', 'Incumplido')], default='PENDIENTE', max_length=20)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos', to='asignaciones.asignacion')),
                ('historialEstadoEntrega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos', to='entregas.historialestadoentrega')),
            ],
            options={
                'verbose_name': 'seguimiento entrega',
                'verbose_name_plural': 'seguimientos entrega',
            },
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaNovedad', models.DateField(auto_now_add=True)),
                ('descripcionNovedad', models.CharField(help_text='Ingrese la descripción de la novedad', max_length=300)),
                ('solucionNovedad', models.CharField(blank=True, help_text='Ingrese la solución de la novedad', max_length=300, null=True)),
                ('tipoEstado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estados_novedad', to='core.tipomaestra')),
                ('tipoNovedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_novedad', to='core.tipomaestra')),
                ('seguimientoEntrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='entregas.seguimientoentrega')),
            ],
            options={
                'verbose_name': 'novedad',
                'verbose_name_plural': 'novedades',
            },
        ),
    ]
