# Generated by Django 5.2.14 on 2026-05-25 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0002_alter_asignacion_options_and_more'),
        ('core', '0002_alter_tipomaestra_options_and_more'),
        ('entregas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialestadoentrega',
            options={'ordering': ['-fechaCambioHistorial', '-id'], 'verbose_name': 'historial estado entrega', 'verbose_name_plural': 'historial estados entrega'},
        ),
        migrations.AlterModelOptions(
            name='novedad',
            options={'ordering': ['-fechaNovedad', '-id'], 'verbose_name': 'novedad', 'verbose_name_plural': 'novedades'},
        ),
        migrations.AlterModelOptions(
            name='seguimientoentrega',
            options={'ordering': ['-fechaEstimadaSeguimiento', '-id'], 'verbose_name': 'seguimiento entrega', 'verbose_name_plural': 'seguimientos entrega'},
        ),
        migrations.AlterField(
            model_name='historialestadoentrega',
            name='fechaCambioHistorial',
            field=models.DateTimeField(auto_now_add=True, db_column='HIES_FECHA_CAMBIO'),
        ),
        migrations.AlterField(
            model_name='historialestadoentrega',
            name='id',
            field=models.AutoField(db_column='HIES_ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historialestadoentrega',
            name='observacionHistorial',
            field=models.CharField(blank=True, db_column='HIES_OBSERVACION', help_text='Ingrese una observación', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='historialestadoentrega',
            name='tipoEstado',
            field=models.ForeignKey(db_column='TIPO_ESTADO', on_delete=django.db.models.deletion.PROTECT, related_name='estados_historial_entrega', to='core.tipomaestra'),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='descripcionNovedad',
            field=models.CharField(db_column='NOVE_DESCRIPCION', help_text='Ingrese la descripción de la novedad', max_length=300),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='fechaNovedad',
            field=models.DateField(auto_now_add=True, db_column='NOVE_FECHA'),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='id',
            field=models.AutoField(db_column='NOVE_ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='seguimientoEntrega',
            field=models.ForeignKey(db_column='SEGU_ID', on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='entregas.seguimientoentrega'),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='solucionNovedad',
            field=models.CharField(blank=True, db_column='NOVE_SOLUCION', help_text='Ingrese la solución de la novedad', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='tipoEstado',
            field=models.ForeignKey(db_column='TIPO_ESTADO', on_delete=django.db.models.deletion.PROTECT, related_name='estados_novedad', to='core.tipomaestra'),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='tipoNovedad',
            field=models.ForeignKey(db_column='TIPO_NOVEDAD', on_delete=django.db.models.deletion.PROTECT, related_name='tipos_novedad', to='core.tipomaestra'),
        ),
        migrations.AlterField(
            model_name='seguimientoentrega',
            name='asignacion',
            field=models.ForeignKey(db_column='ASIG_ID', on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos', to='asignaciones.asignacion'),
        ),
        migrations.AlterField(
            model_name='seguimientoentrega',
            name='cumplimientoSeguimiento',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('A_TIEMPO', 'A tiempo'), ('CON_RETRASO', 'Con retraso')], db_column='SEGU_CUMPLIMIENTO', default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='seguimientoentrega',
            name='fechaEstimadaSeguimiento',
            field=models.DateTimeField(db_column='SEGU_FECHA_ESTIMADA', help_text='Ingrese la fecha estimada de entrega'),
        ),
        migrations.AlterField(
            model_name='seguimientoentrega',
            name='fechaRealSeguimiento',
            field=models.DateTimeField(blank=True, db_column='SEGU_FECHA_REAL', help_text='Ingrese la fecha real de entrega', null=True),
        ),
        migrations.AlterField(
            model_name='seguimientoentrega',
            name='historialEstadoEntrega',
            field=models.ForeignKey(db_column='HIES_ID', on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos', to='entregas.historialestadoentrega'),
        ),
        migrations.AlterField(
            model_name='seguimientoentrega',
            name='id',
            field=models.AutoField(db_column='SEGU_ID', primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='historialestadoentrega',
            table='TBL_HISTORIAL_ESTADOS_ENTREGA',
        ),
        migrations.AlterModelTable(
            name='novedad',
            table='TBL_NOVEDADES',
        ),
        migrations.AlterModelTable(
            name='seguimientoentrega',
            table='TBL_SEGUIMIENTO_ENTREGA',
        ),
    ]
