# Generated by Django 5.2.14 on 2026-05-24 23:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UbicacionDomiciliario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitudUbicacion', models.DecimalField(decimal_places=8, help_text='Ingrese la latitud', max_digits=10, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitudUbicacion', models.DecimalField(decimal_places=8, help_text='Ingrese la longitud', max_digits=11, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('fechaHoraUbicacion', models.DateTimeField(auto_now_add=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='asignaciones.asignacion')),
            ],
            options={
                'verbose_name': 'ubicación domiciliario',
                'verbose_name_plural': 'ubicaciones domiciliarios',
                'ordering': ['-fechaHoraUbicacion'],
            },
        ),
    ]
