# Generated by Django 5.2.14 on 2026-05-25 22:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0002_alter_asignacion_options_and_more'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicaciondomiciliario',
            name='asignacion',
            field=models.ForeignKey(db_column='ASIG_ID', on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='asignaciones.asignacion'),
        ),
        migrations.AlterField(
            model_name='ubicaciondomiciliario',
            name='fechaHoraUbicacion',
            field=models.DateTimeField(auto_now_add=True, db_column='UBIC_FECHA_HORA'),
        ),
        migrations.AlterField(
            model_name='ubicaciondomiciliario',
            name='id',
            field=models.AutoField(db_column='UBIC_ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ubicaciondomiciliario',
            name='latitudUbicacion',
            field=models.DecimalField(db_column='UBIC_LATITUD', decimal_places=8, help_text='Ingrese la latitud', max_digits=10, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='ubicaciondomiciliario',
            name='longitudUbicacion',
            field=models.DecimalField(db_column='UBIC_LONGITUD', decimal_places=8, help_text='Ingrese la longitud', max_digits=11, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterModelTable(
            name='ubicaciondomiciliario',
            table='TBL_UBICACIONES_DOMICILIARIO',
        ),
    ]
