# Generated by Django 5.2.14 on 2026-05-24 23:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacionCliente', models.CharField(help_text='Ingrese la identificación del cliente', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Este campo solo debe contener números.', regex='^\\d+$')])),
                ('nombresCliente', models.CharField(help_text='Ingrese los nombres del cliente', max_length=100)),
                ('apellidosCliente', models.CharField(help_text='Ingrese los apellidos del cliente', max_length=100)),
                ('telefonoCliente', models.CharField(help_text='Ingrese el teléfono del cliente', max_length=12, validators=[django.core.validators.RegexValidator(message='Este campo solo debe contener números.', regex='^\\d+$')])),
                ('correoCliente', models.EmailField(help_text='Ingrese el correo del cliente', max_length=100, unique=True)),
                ('direccionCliente', models.CharField(help_text='Ingrese la dirección del cliente', max_length=200)),
                ('passwordCliente', models.CharField(help_text='Ingrese el password del cliente', max_length=100)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Domiciliario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacionDomiciliario', models.CharField(help_text='Ingrese la identificación del domiciliario', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Este campo solo debe contener números.', regex='^\\d+$')])),
                ('nombresDomiciliario', models.CharField(help_text='Ingrese los nombres del domiciliario', max_length=100)),
                ('apellidosDomiciliario', models.CharField(help_text='Ingrese los apellidos del domiciliario', max_length=100)),
                ('telefonoDomiciliario', models.CharField(help_text='Ingrese el teléfono del domiciliario', max_length=12, validators=[django.core.validators.RegexValidator(message='Este campo solo debe contener números.', regex='^\\d+$')])),
                ('tipoVehiculoDomiciliario', models.CharField(help_text='Ingrese el tipo de vehículo', max_length=50)),
                ('placaDomiciliario', models.CharField(help_text='Ingrese la placa del vehículo', max_length=6, unique=True, validators=[django.core.validators.RegexValidator(message='La placa debe tener el formato ABC123.', regex='^[A-Z]{3}[0-9]{3}$')])),
            ],
            options={
                'verbose_name': 'domiciliario',
                'verbose_name_plural': 'domiciliarios',
            },
        ),
    ]
