# Generated by Django 5.2.14 on 2026-05-25 22:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tipomaestra_options_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombresCliente', 'apellidosCliente'], 'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
        migrations.AlterModelOptions(
            name='domiciliario',
            options={'ordering': ['nombresDomiciliario', 'apellidosDomiciliario'], 'verbose_name': 'domiciliario', 'verbose_name_plural': 'domiciliarios'},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='passwordCliente',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellidosCliente',
            field=models.CharField(db_column='CLIE_APELLIDOS', help_text='Ingrese los apellidos del cliente', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correoCliente',
            field=models.EmailField(db_column='CLIE_CORREO', help_text='Ingrese el correo del cliente', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccionCliente',
            field=models.CharField(db_column='CLIE_DIRECCION', help_text='Ingrese la dirección del cliente', max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.AutoField(db_column='CLIE_ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='identificacionCliente',
            field=models.CharField(db_column='CLIE_IDENTIFICACION', help_text='Ingrese la identificación del cliente', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Este campo solo debe contener números.', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombresCliente',
            field=models.CharField(db_column='CLIE_NOMBRES', help_text='Ingrese los nombres del cliente', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefonoCliente',
            field=models.CharField(db_column='CLIE_TELEFONO', help_text='Ingrese el teléfono del cliente', max_length=20, validators=[django.core.validators.RegexValidator(message='Este campo solo debe contener números.', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='domiciliario',
            name='apellidosDomiciliario',
            field=models.CharField(db_column='DOMI_APELLIDOS', help_text='Ingrese los apellidos del domiciliario', max_length=100),
        ),
        migrations.AlterField(
            model_name='domiciliario',
            name='id',
            field=models.AutoField(db_column='DOMI_ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='domiciliario',
            name='identificacionDomiciliario',
            field=models.CharField(db_column='DOMI_IDENTIFICACION', help_text='Ingrese la identificación del domiciliario', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Este campo solo debe contener números.', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='domiciliario',
            name='nombresDomiciliario',
            field=models.CharField(db_column='DOMI_NOMBRES', help_text='Ingrese los nombres del domiciliario', max_length=100),
        ),
        migrations.AlterField(
            model_name='domiciliario',
            name='placaDomiciliario',
            field=models.CharField(db_column='DOMI_PLACA', help_text='Ingrese la placa del vehículo', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='La placa solo debe contener letras, números o guiones.', regex='^[A-Z0-9-]+$')]),
        ),
        migrations.AlterField(
            model_name='domiciliario',
            name='telefonoDomiciliario',
            field=models.CharField(db_column='DOMI_TELEFONO', help_text='Ingrese el teléfono del domiciliario', max_length=20, validators=[django.core.validators.RegexValidator(message='Este campo solo debe contener números.', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='domiciliario',
            name='tipoVehiculoDomiciliario',
            field=models.CharField(db_column='DOMI_TIPO_VEHICULO', help_text='Ingrese el tipo de vehículo', max_length=50),
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='TBL_CLIENTES',
        ),
        migrations.AlterModelTable(
            name='domiciliario',
            table='TBL_DOMICILIARIOS',
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(db_column='USUA_ID', primary_key=True, serialize=False)),
                ('usernameUsuario', models.CharField(db_column='USUA_USERNAME', help_text='Ingrese el nombre de usuario', max_length=50, unique=True)),
                ('passwordUsuario', models.CharField(db_column='USUA_PASSWORD', help_text='Ingrese el password del usuario', max_length=255)),
                ('activoUsuario', models.BooleanField(db_column='USUA_ACTIVO', default=True)),
                ('cliente', models.ForeignKey(blank=True, db_column='CLIE_ID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='usuarios.cliente')),
                ('domiciliario', models.ForeignKey(blank=True, db_column='DOMI_ID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='usuarios.domiciliario')),
                ('tipoRol', models.ForeignKey(db_column='TIPO_ROL', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios_rol', to='core.tipomaestra')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'TBL_USUARIOS',
                'ordering': ['usernameUsuario'],
            },
        ),
    ]
