# Generated by Django 5.2.14 on 2026-05-24 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('solicitudes', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPublicacionSolicitudDisponible', models.DateTimeField(auto_now_add=True)),
                ('fechaAceptacionSolicitudDisponible', models.DateTimeField(blank=True, null=True)),
                ('domiciliario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_aceptadas', to='usuarios.domiciliario')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibles', to='solicitudes.solicitud')),
                ('tipoEstado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estados_solicitud_disponible', to='core.tipomaestra')),
            ],
            options={
                'verbose_name': 'solicitud disponible',
                'verbose_name_plural': 'solicitudes disponibles',
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAsignacion', models.DateField(auto_now_add=True)),
                ('solicitudDisponible', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='asignacion', to='asignaciones.solicituddisponible')),
            ],
            options={
                'verbose_name': 'asignación',
                'verbose_name_plural': 'asignaciones',
            },
        ),
    ]
