# Generated by Django 5.2.14 on 2026-05-25 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0001_initial'),
        ('core', '0002_alter_tipomaestra_options_and_more'),
        ('solicitudes', '0002_alter_solicitud_options_alter_solicitud_cliente_and_more'),
        ('usuarios', '0002_alter_cliente_options_alter_domiciliario_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacion',
            options={'ordering': ['-fechaAsignacion', '-id'], 'verbose_name': 'asignación', 'verbose_name_plural': 'asignaciones'},
        ),
        migrations.AlterModelOptions(
            name='solicituddisponible',
            options={'ordering': ['-fechaPublicacionSolicitudDisponible', '-id'], 'verbose_name': 'solicitud disponible', 'verbose_name_plural': 'solicitudes disponibles'},
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='fechaAsignacion',
            field=models.DateField(auto_now_add=True, db_column='ASIG_FECHA'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='id',
            field=models.AutoField(db_column='ASIG_ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='solicitudDisponible',
            field=models.OneToOneField(db_column='SOLI_DISP_ID', on_delete=django.db.models.deletion.PROTECT, related_name='asignacion', to='asignaciones.solicituddisponible'),
        ),
        migrations.AlterField(
            model_name='solicituddisponible',
            name='domiciliario',
            field=models.ForeignKey(blank=True, db_column='DOMI_ID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_aceptadas', to='usuarios.domiciliario'),
        ),
        migrations.AlterField(
            model_name='solicituddisponible',
            name='fechaAceptacionSolicitudDisponible',
            field=models.DateTimeField(blank=True, db_column='SOLI_DISP_FECHA_ACEP', null=True),
        ),
        migrations.AlterField(
            model_name='solicituddisponible',
            name='fechaPublicacionSolicitudDisponible',
            field=models.DateTimeField(auto_now_add=True, db_column='SOLI_DISP_FECHA_PUB'),
        ),
        migrations.AlterField(
            model_name='solicituddisponible',
            name='id',
            field=models.AutoField(db_column='SOLI_DISP_ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solicituddisponible',
            name='solicitud',
            field=models.ForeignKey(db_column='SOLI_ID', on_delete=django.db.models.deletion.CASCADE, related_name='disponibles', to='solicitudes.solicitud'),
        ),
        migrations.AlterField(
            model_name='solicituddisponible',
            name='tipoEstado',
            field=models.ForeignKey(db_column='TIPO_ESTADO', on_delete=django.db.models.deletion.PROTECT, related_name='estados_solicitud_disponible', to='core.tipomaestra'),
        ),
        migrations.AlterModelTable(
            name='asignacion',
            table='TBL_ASIGNACIONES',
        ),
        migrations.AlterModelTable(
            name='solicituddisponible',
            table='TBL_SOLICITUDES_DISPONIBLES',
        ),
    ]
